#!/bin/sh

## Copyright (C) 2019 - 2023 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

set -o allexport

GRUB_DEVICE="/dev/disk/by-uuid/${GRUB_DEVICE_UUID}"
unset GRUB_DEVICE_UUID

## initramfs support
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX boot=live plainroot union=overlay ip=frommedia noeject nopersistence"

## dracut support
## https://www.kicksecure.com/wiki/Grub-live#Developer_Information
##
## using Debian forked upstream module 90overlay-root (tested)
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX rootovl"
## using dracut upstream module 90overlayfs (untested)
#GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX rd.live.overlay.overlayfs=1 rd.live.overlay.readonly=1"

GRUB_DISTRIBUTOR="LIVE mode USER (For daily activities.)"
GRUB_DISABLE_RECOVERY="true"

## Cannot use '&>' because it is a bashism.
if [ "$(dpkg-query -W -f='${db:Status-Status}' initramfs-tools 2>/dev/null)" = "installed" ] ; then
   ## https://forums.whonix.org/t/bullseye-live-boot-needs-grub-disable-linux-uuid-true-parameter-in-etc-grub-d-11-linux-live/9066
   ## https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994138
   ## https://askubuntu.com/a/283320
   GRUB_DISABLE_LINUX_UUID="true"
elif [ "$(dpkg-query -W -f='${db:Status-Status}' dracut 2>/dev/null)" = "installed" ] ; then
   if ! test -x /usr/lib/dracut/modules.d/90overlay-root/overlay-mount.sh ; then
      echo "\
grub-live $0: ERROR: It has been detected that this system is using dracut but but file /usr/lib/dracut/modules.d/90overlay-root/overlay-mount.sh is not executable. This means that no live mode boot menu entry will be added.
" >&2
      exit 0
   fi
else
   echo "\
grub-live $0: ERROR: Neither initramfs-tools nor dracut is installed. Support for other initrd generators is not implemented. This means that no live mode boot menu entry will be added.
" >&2
   exit 0
fi

if test -x /etc/grub.d/10_linux ; then
	/etc/grub.d/10_linux
fi
