#!/bin/sh

## Copyright (C) 2019 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

set -o allexport

GRUB_DEVICE="/dev/disk/by-uuid/${GRUB_DEVICE_UUID}"
unset GRUB_DEVICE_UUID

## initramfs support
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX boot=live plainroot union=overlay ip=frommedia noeject nopersistence"

## dracut support
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX rootovl"

GRUB_DISTRIBUTOR="LIVE mode USER (For daily activities.)"
GRUB_DISABLE_RECOVERY="true"

## Cannot use '&>' because it is a bashism.
if dpkg-query --show initramfs-tools 1>/dev/null 2>/dev/null ; then
   ## https://forums.whonix.org/t/bullseye-live-boot-needs-grub-disable-linux-uuid-true-parameter-in-etc-grub-d-11-linux-live/9066
   ## https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994138
   ## https://askubuntu.com/a/283320
   GRUB_DISABLE_LINUX_UUID="true"
fi

if test -x /etc/grub.d/10_linux ; then
	/etc/grub.d/10_linux
fi
